# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool: default
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    sudo docker build -t front-end . 
    

  displayName: 'for building image'

- script: |
    sudo docker tag front-end us-central1-docker.pkg.dev/prj-qa-workshop-poc/piyush-repo/front-end:latest  
     

  displayName: 'for tag'

- script: |
     sudo docker push us-central1-docker.pkg.dev/prj-qa-workshop-poc/piyush-repo/front-end:latest 
      

  displayName: 'for push'

